# https://starship.rs/config/
format = """
$time\
$directory\
$git_branch\
$git_state\
$git_status\
$direnv\
$cmd_duration\
$battery\
$line_break\
$shell\
$character"""

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"

