#!/usr/bin/env bash

if ! command -v brew &> /dev/null; then
    echo "installing brew"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

brew update &> /dev/null
brew install \
    bat \
    bufbuild/buf/buf \
    fzf \
    gh \
    golang-migrate \
    google-cloud-sdk \
    gnupg \
    httpie \
    lua-language-server \
    lsd \
    protobuf \
    postgresql \
    python \
    rg \
    tree \
    watchman \
    universal-ctags \
    yq
    # &> /dev/null

