#!/usr/bin/env bash

if ! command -v node &> /dev/null; then
    echo "installing node"
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash

    nvm install 22
    nvm use 22
    nvm alias default 22
fi

npm i -g pyright

