#!/usr/bin/env bash

if ! command -v nvim &> /dev/null; then
    curl -fsSLO https://github.com/neovim/neovim/releases/download/nightly/nvim-macos-arm64.tar.gz
    tar xzf nvim-macos-arm64.tar.gz
    rm -rf nvim-macos-arm64.tar.gz
    sudo mv nvim-macos-arm64/bin/nvim /usr/local/bin/nvim
fi

rm -rf $XDG_CONFIG_HOME/nvim
ln -s $CMPTR_DIR/env/.config/nvim $XDG_CONFIG_HOME/nvim
