#!/usr/bin/env bash

curl -fsSLO https://github.com/neovim/neovim/releases/download/nightly/nvim-macos-arm64.tar.gz
tar xzf nvim-macos-arm64.tar.gz

# Move the binary
sudo mv nvim-macos-arm64/bin/nvim /usr/local/bin/nvim

# Move the runtime files
sudo mkdir -p /usr/local/share/nvim
sudo mv nvim-macos-arm64/share/nvim/runtime /usr/local/share/nvim/

# Clean up
rm -rf nvim-macos-arm64*

# Set up config symlink
rm -rf $XDG_CONFIG_HOME/nvim
ln -s $CMPTR_DIR/env/.config/nvim $XDG_CONFIG_HOME/nvim
