#!/usr/bin/env bash

# nightly: https://github.com/neovim/neovim/releases/download/nightly/nvim-macos-arm64.tar.gz
curl -fsSLO https://github.com/neovim/neovim/releases/latest/download/nvim-macos-arm64.tar.gz
tar xzf nvim-macos-arm64.tar.gz

# Move the binary
rm /usr/local/bin/nvim
sudo mv nvim-macos-arm64/bin/nvim /usr/local/bin/nvim

# Move the runtime files
rm -rf /usr/local/share/nvim
sudo mkdir -p /usr/local/share/nvim
sudo mv nvim-macos-arm64/share/nvim/runtime /usr/local/share/nvim/

# Clean up
rm nvim-macos-arm64.tar.gz
rm -rf nvim-macos-arm64

# Set up config symlink
rm -rf $XDG_CONFIG_HOME/nvim
ln -s $CMPTR_DIR/env/.config/nvim $XDG_CONFIG_HOME/nvim

