#!/usr/bin/env bash

if ! command -v brew &> /dev/null; then
    echo "installing brew"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

brew update &> /dev/null
brew install postgresql

ln -sf "$CMPTR_DIR/env/.psqlrc" "$HOME/.psqlrc"
