#!/usr/bin/env bash

if ! command -v cargo &> /dev/null
then
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
    source "$HOME/.cargo/env"
fi

if ! command -v rust-analyzer &> /dev/null
then
    curl -L https://github.com/rust-lang/rust-analyzer/releases/latest/download/rust-analyzer-aarch64-apple-darwin.gz | gunzip -c - > $HOME/.local/bin/rust-analyzer
    chmod +x $HOME/.local/bin/rust-analyzer
fi
cargo install stylua --features luajit

