#!/usr/bin/env bash

export ZSH="$HOME/.oh-my-zsh"
export ZSH_CUSTOM="$HOME/.oh-my-zsh/custom"

# Install oh-my-zsh if not installed
if [ ! -d "$HOME/.oh-my-zsh" ]; then
    echo "installing oh-my-zsh"
    curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh | sh > /dev/null 2>&1
fi

# Install starship if not installed
if ! command -v starship &> /dev/null; then
    echo "installing starship"
    curl -sS https://starship.rs/install.sh | sh -s -- -y
fi

echo "zsh custom dir: $ZSH_CUSTOM"

#  link any files starting with .zsh in the env directory to the home directory
for file in $(find env -name ".zsh*"); do
    filename=$(basename $file)
    echo "linking home $filename to $HOME/$filename"
    ln -sf "$CMPTR_DIR/$file" "$HOME/$filename"
done

# link any files ending in .zsh in the env directory to ZSH_CUSTOM dir
for file in $(find env -name "*.zsh"); do
    filename=$(basename $file)
    echo "linking custom $filename to $ZSH_CUSTOM/$filename"
    ln -sf "$CMPTR_DIR/$file" "$ZSH_CUSTOM/$filename"
done

for file in $(find env -name ".git*" -type f); do
    filename=$(basename $file)
    echo "linking home $filename to $HOME/$filename"
    ln -sf "$CMPTR_DIR/$file" "$HOME/$filename"
done

# Ensure starship config directory exists
mkdir -p "$XDG_CONFIG_HOME"
ln -sf "$CMPTR_DIR/env/.config/starship" "$XDG_CONFIG_HOME/"

echo "launching zsh"
zsh -l
